# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SusanaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SusanaApp

	pod 'Charts'
	pod 'Alamofire', '~> 5.5'

end
